# This will run on Travis' 'new' container-based infrastructure
sudo: false

os: linux

language: cpp

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: OscProb
    - DOXYFILE: $TRAVIS_BUILD_DIR
    - GH_REPO_REF: github.com/joaoabcoelho/OscProb.git

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - root-system

# Build your code e.g. by calling make
script:
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
